
package tn.esprit.client;

import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReservationService", targetNamespace = "http://gestionReservation/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationService {


    /**
     * 
     * @param date
     * @param nom
     * @param nombrePersonnes
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterReservation", targetNamespace = "http://gestionReservation/", className = "tn.esprit.client.AjouterReservation")
    @ResponseWrapper(localName = "ajouterReservationResponse", targetNamespace = "http://gestionReservation/", className = "tn.esprit.client.AjouterReservationResponse")
    @Action(input = "http://gestionReservation/ReservationService/ajouterReservationRequest", output = "http://gestionReservation/ReservationService/ajouterReservationResponse")
    public String ajouterReservation(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "nombrePersonnes", targetNamespace = "")
        int nombrePersonnes);

    /**
     * 
     * @return
     *     returns java.util.List<tn.esprit.client.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listerReservations", targetNamespace = "http://gestionReservation/", className = "tn.esprit.client.ListerReservations")
    @ResponseWrapper(localName = "listerReservationsResponse", targetNamespace = "http://gestionReservation/", className = "tn.esprit.client.ListerReservationsResponse")
    @Action(input = "http://gestionReservation/ReservationService/listerReservationsRequest", output = "http://gestionReservation/ReservationService/listerReservationsResponse")
    public List<Reservation> listerReservations();

    /**
     * 
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "annulerReservation", targetNamespace = "http://gestionReservation/", className = "tn.esprit.client.AnnulerReservation")
    @ResponseWrapper(localName = "annulerReservationResponse", targetNamespace = "http://gestionReservation/", className = "tn.esprit.client.AnnulerReservationResponse")
    @Action(input = "http://gestionReservation/ReservationService/annulerReservationRequest", output = "http://gestionReservation/ReservationService/annulerReservationResponse")
    public String annulerReservation(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom);

}
